openapi: 3.0.0
info:
  version: 1.0.0
  title: LBAW MediaLibrary Web API
  description: Web Resources Specification (A7) for MediaLibrary
servers:
  - url: https://git.fe.up.pt./lbaw/lbaw2324
    description: Production server
externaldocs:
  description: Find out more about our project here.
  url: https://git.fe.up.pt./lbaw/lbaw2324
tags:
  - name: M01-Authentication and Individual Profile.
    description:
      "Web resources associated with user authentication. Includes the following
      system features: login/logout, registration, view and edit personal
      profile information."
  - name: M02-Event.
    description:
      "Web resources associated with events. Includes the following system
      features: view,edit and delete events."
  - name: M03-Participants.
    description: "Web resources associated with event participation management. Includes the following system features: view, add and remove participants of specific event."
paths:
  /login:
    post:
      operationId: R101
      summary: Login
      description: "Login. Access: PUB"
      tags:
        - M01-Authentication and Individual Profile.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login successful
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 123
                      username:
                        type: string
                        example: john_doe
                      email:
                        type: string
                        example: john.doe@example.com
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid credentials
  /logout:
    post:
      operationId: R102
      summary: Logout
      description: "Logout. Access: USER"
      tags:
        - M01-Authentication and Individual Profile.
      responses:
        "200":
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Logout successful
        "400":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid Credentials
  /register:
    post:
      operationId: R103
      summary: Register
      description: "Register. Access: PUB"
      tags:
        - M01-Authentication and Individual Profile.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
                - username
                - email
                - password
                - password_confirmation
      responses:
        "200":
          description: Registration successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Registration successful
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 123
                      username:
                        type: string
                        example: john_doe
                      email:
                        type: string
                        example: john.doe@example.com
        "400":
          description: Invalid data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid data
        "403":
          description: Already registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Already registered
  /profile:
    get:
      operationId: R104
      summary: Get profile
      description: "Get profile. Access: USER"
      tags:
        - M01-Authentication and Individual Profile.
      responses:
        "200":
          description: Profile information
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 123
                  username:
                    type: string
                    example: john_doe
                  email:
                    type: string
                    example: null
        "403":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
  /create_event:
    post:
      operationId: R201
      summary: Create event
      description: "Create event. Access: USER"
      tags:
        - M02-Event.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                date:
                  type: string
                capacity:
                  type: integer
                ticket-limit:
                  type: integer
                owner_id:
                  type: integer
              required:
                - name
                - description
                - date
                - time
                - location
                - image
      responses:
        "200":
          description: Event created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Event created
                  event:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 123
                      name:
                        type: string>
                        example: Event name
                      description:
                        type: string
                        example: Event description
                      date:
                        type: string
                        example: 2020-12-12
                      time:
                        type: string
                        example: 12:00:00
                      location:
                        type: string
                        example: Event location
                      image:
                        type: string
                        example: Event image
        "400":
          description: Invalid data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid data
        "403":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized

  /delete_event:
    post:
      operationId: R202
      summary: Delete event
      description: "Delete event. Access: OWN&ADM"
      tags:
        - M02-Event.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event_id:
                  type: integer
              required:
                - event_id
      responses:
        "200":
          description: Event deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Event deleted
        "400":
          description: Invalid data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid data
        "403":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
  /edit_event:
    post:
      operationId: R203
      summary: Edit event
      description: "Edit event. Access: OWN&ADM"
      tags:
        - M02-Event.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                event_id:
                  type: integer
                name:
                  type: string
                description:
                  type: string
                date:
                  type: string
                time:
                  type: string
                location:
                  type: string
                image:
                  type: string
              required:
                - event_id
                - name
                - description
                - date
                - time
                - location
                - image
      responses:
        "200":
          description: Event edited
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Event edited
                  event:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 123
                      name:
                        type: string>
                        example: Event name
                      description:
                        type: string
                        example: Event description
                      date:
                        type: string
                        example: 2020-12-12
                      time:
                        type: string
                        example: 12:00:00
                      location:
                        type: string
                        example: Event location
                      image:
                        type: string
                        example: Event image
        "400":
          description: Invalid data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid data
        "403":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
  /event:
    get:
      operationId: R204
      summary: Get event
      description: "Get event. Access: PUB"
      tags:
        - M02-Event.
      responses:
        "200":
          description: Event information
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 123
                  name:
                    type: string
                    example: Event name
                  description:
                    type: string
                    example: Event description
                  date:
                    type: string
                    example: 2020-12-12
                  time:
                    type: string
                    example: 12:00:00
                  location:
                    type: string
                    example: Event location
                  image:
                    type: string
                    example: Event image
        "400":
          description: Invalid data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid data
  /add_participant:
    post:
      operationId: R301
      summary: Add participant
      description: "Add participant. Access: OWN&ADM"
      tags:
        - M03-Participants.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event_id:
                  type: integer
                user_id:
                  type: integer
              required:
                - event_id
                - user_id
      responses:
        "200":
          description: Participant added
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Participant added
                  participant:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 123
        "400":
          description: Invalid data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid data
        "403":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
  /remove_participant:
    post:
      operationId: R302
      summary: Remove participant
      description: "Remove participant. Access: OWN&ADM"
      tags:
        - M03-Participants.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event_id:
                  type: integer
                user_id:
                  type: integer
              required:
                - event_id
                - user_id
      responses:
        "200":
          description: Participant removed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Participant removed
                  participant:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 123
        "400":
          description: Invalid data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid data
        "403":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
  /view_participants:
    get:
      operationId: R302
      summary: View participants
      description: "View participants. Access: PUB"
      tags:
        - M03-Participants.
      responses:
        "200":
          description: Participants information
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: array
                    example: 1,2,3
        "400":
          description: Invalid data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid data
